project 'Simple-chatApp-API.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Simple-chatApp-API' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Simple-chatApp-API

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Socket.IO-Client-Swift'
  
  target 'Simple-chatApp-APITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Simple-chatApp-APIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
